require("common.plugins")
require("common.general")
require("common.options")
require("common.mappings")

-- load plugin config
require("modules.alpha-nvim")
require("modules.web-devicons")
require("modules.bufferline")
require("modules.config-local")
require("modules.floaterm")
require("modules.flutter")
require("modules.gitsigns")
require("modules.local-highlight")
require("modules.mason")
require("modules.nlsp-settings")
require("modules.notifier")
require("modules.null-ls")
require("modules.nvim-autopairs")
require("modules.nvim-cmp")
require("modules.nvim-comment")
require("modules.nvim-colorizer")
-- require("modules.nvim-dap")
require("modules.nvim-lualine")
require("modules.nvim-lspconfig")
require("modules.nvim-lsputils")
require("modules.nvim-navic")
require("modules.nvim-tree")
require("modules.nvim-scrollbar")
require("modules.nvim-ufo")
require("modules.telescope")
require("modules.treesitter")
require("modules.vim-blade")
require("modules.vim-which-key")
