require("common.plugins")
require("common.general")
require("common.options")
require("common.mappings")

-- load modules
require("presence")
require("color-picker")

-- load plugin config
require("modules.web-devicons")
require("modules.bufferline")
require("modules.fidget")
require("modules.floaterm")
require("modules.gitsigns")
require("modules.mason")
require("modules.nlsp-settings")
require("modules.null-ls")
require("modules.nvim-autopairs")
require("modules.nvim-cmp")
require("modules.nvim-comment")
require("modules.nvim-colorizer")
require("modules.nvim-dap")
require("modules.nvim-lualine")
require("modules.nvim-lspconfig")
require("modules.nvim-lsputils")
require("modules.nvim-tree")
require("modules.telescope")
require("modules.treesitter")
require("modules.vim-blade")
require("modules.vim-which-key")
