require('common.plugins')
require('common.settings')
require('common.mappings')
require('common.lsp-config')
require('modules.blade')
require('modules.compe')
require('modules.lightline')
require('modules.nvim-tree')
