vim.keymap.set("n", "<leader>k", "<CMD>w<CR>", { desc = "Write buffer", noremap = true })
vim.keymap.set("n", "<localleader>w", "<CMD>w<CR>", { desc = "Write buffer", noremap = true })
vim.keymap.set("n", "<leader>ll", "<CMD>Lazy<CR>", { desc = "Lazy" })
vim.keymap.set("n", "<esc>", "<CMD>noh<CR>", { desc = "Clear Highlights" })
vim.keymap.set("n", "<localleader>h", "<CMD>noh<CR>", { desc = "Clear Highlights" })
vim.keymap.set("i", "kj", "<esc>", { desc = "Escape" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
